[package]
name = "schnorr_initializerless_account_contract"
type = "contract"
compiler_version = ">=1.0.0"
authors = [""]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-nr", tag="v4.4.0-nightly.20260522", directory="aztec" }
schnorr = { git = "https://github.com/noir-lang/schnorr", tag = "v0.2.0" }
immutables = { path = "../immutables" }
