[workspace]
members = [
    "./subscription-fpc",
    "./ecdsa_account_deployer",
    "./schnorr_initializerless_account",
    "./simulated_schnorr_initializerless_account",
    "./token",
    "./amm",
    "./proof_of_password"
]