#!/usr/bin/env bash
# Compiles the Solidity contract and generates TypeScript artifacts.
# Usage: cd packages/contracts/ethereum/solidity && ./generate-artifacts.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Resolve `forge`. aztec-up installs it at ~/.aztec/current/internal-bin/ but no
# longer puts that directory on PATH, so the bare `forge` lookup fails for users
# who don't also have foundryup. Order: $FORGE override → aztec-up → PATH.
FORGE="${FORGE:-$HOME/.aztec/current/internal-bin/forge}"
if [ ! -x "$FORGE" ]; then
  if command -v forge >/dev/null 2>&1; then
    FORGE=forge
  else
    echo "error: forge not found at $HOME/.aztec/current/internal-bin/forge or on PATH" >&2
    echo "install aztec-up or foundryup, or set FORGE=/path/to/forge" >&2
    exit 1
  fi
fi

echo "Compiling with $FORGE..."
"$FORGE" build

ARTIFACT="out/GoBridge.sol/GoBridge.json"
OUTPUT_DIR="../generated"
OUTPUT="$OUTPUT_DIR/bridge-contract-artifacts.ts"

mkdir -p "$OUTPUT_DIR"

echo "Generating TypeScript artifacts..."
python3 -c "
import json

with open('$ARTIFACT') as f:
    d = json.load(f)

abi = [e for e in d['abi'] if e.get('type') == 'function']
bytecode = '0x' + d['bytecode']['object'][2:]

print('// Auto-generated by generate-artifacts.sh — do not edit manually')
print('import type { Hex } from \"viem\";')
print()
print('export const BRIDGE_CONTRACT_ABI = ' + json.dumps(abi, indent=2) + ' as const;')
print()
print('export const BRIDGE_CONTRACT_BYTECODE = \"' + bytecode + '\" as Hex;')
" > "$OUTPUT"

echo "Written to $OUTPUT"
